export const SET_USERNAME = "SET_USERNAME";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";

export const SEND_MESSAGE = "SEND_MESSAGE";

export const FIREBASE_LOG_MESSAGE = "FIREBASE_LOG_MESSAGE";
export const FIREBASE_LOG_MESSAGE_SUCCESS = "FIREBASE_LOG_MESSAGE_SUCCESS";
export const FIREBASE_LOG_MESSAGE_FAILED = "FIREBASE_LOG_MESSAGE_FAILED";
